// Focused check for NR-028's shared program-like filter (design-spec §FR-004a).
//
// Pure value logic: the module never includes <windows.h>, so this test builds
// and runs without creating a window or initializing COM.

#include "catalog/app_filter.h"

#include <cstdio>
#include <cstdlib>
#include <string>

using nimblerun::IsProgramLikeTarget;

namespace {

void Expect(bool condition, const char* message) {
    if (!condition) {
        std::fprintf(stderr, "FAILED: %s\n", message);
        std::exit(1);
    }
}

void ExpectProgramLike(const wchar_t* target, const char* message) {
    Expect(IsProgramLikeTarget(target), message);
}

void ExpectNotProgramLike(const wchar_t* target, const char* message) {
    Expect(!IsProgramLikeTarget(target), message);
}

void TestAumid() {
    ExpectProgramLike(L"com.squirrel.GitHubDesktop.GitHubDesktop",
                      "bare AUMID is program-like");
    ExpectProgramLike(L"Microsoft.AutoGenerated.{96C20C2F-ADE8-25BC-3905-2F710401DE32}",
                      "auto-generated AUMID is program-like");
}

void TestAumidDotsAreNotExtensions() {
    // Regression: a naive "last dot = extension" parse would treat the trailing
    // "!App" segment as a file extension and drop these packaged apps. The only
    // reliable AUMID/path boundary is the presence of a path separator.
    ExpectProgramLike(L"Microsoft.WindowsCalculator_8wekyb3d8bbwe!App",
                      "Calculator AUMID with dots is program-like");
    ExpectProgramLike(L"Microsoft.BingWeather_8wekyb3d8bbwe!App",
                      "BingWeather AUMID with dots is program-like");
    ExpectProgramLike(L"Microsoft.WindowsTerminal_8wekyb3d8bbwe!App",
                      "Windows Terminal AUMID with dots is program-like");
}

void TestPathWhitelistHits() {
    ExpectProgramLike(L"{6D809377-6AF0-444B-8957-A3773F02200E}\\TightVNC\\tvnserver.exe",
                      "GUID-relative exe is program-like");
    ExpectProgramLike(L"C:\\Tools\\a.com", "com is program-like");
    ExpectProgramLike(L"C:\\Tools\\a.bat", "bat is program-like");
    ExpectProgramLike(L"C:\\Tools\\a.cmd", "cmd is program-like");
    ExpectProgramLike(L"C:\\Tools\\a.lnk", "lnk is program-like");
    ExpectProgramLike(L"C:\\Tools\\a.appref-ms", "appref-ms is program-like");
    ExpectProgramLike(L"C:\\Windows\\System32\\compmgmt.msc", "msc is program-like");
    ExpectProgramLike(L"C:\\Tools\\a.EXE", "uppercase EXE is program-like");
    ExpectProgramLike(L"C:\\Tools\\a.Lnk", "mixed-case Lnk is program-like");
}

void TestPathWhitelistMisses() {
    ExpectNotProgramLike(L"{7C5A40EF-96BC-48C3-88F4-0B6D1E1C6B4C}\\AutoIt3\\AutoIt.chm",
                         "chm help file is not program-like");
    ExpectNotProgramLike(L"C:\\Tools\\AutoIt v3 Website.url", "url website is not program-like");
    ExpectNotProgramLike(L"C:\\Tools\\readme.txt", "txt is not program-like");
    ExpectNotProgramLike(L"C:\\Tools\\manual.pdf", "pdf is not program-like");
    ExpectNotProgramLike(L"C:\\Tools\\notes.rtf", "rtf is not program-like");
    ExpectNotProgramLike(L"C:\\Tools\\index.html", "html is not program-like");
    ExpectNotProgramLike(L"C:\\Tools\\a.msi", "msi installer is not program-like");
    ExpectNotProgramLike(L"C:\\Tools\\script.ps1", "ps1 is not program-like");
    ExpectNotProgramLike(L"C:\\Tools\\noext", "path without an extension is not program-like");
}

void TestUrlScheme() {
    ExpectNotProgramLike(L"https://example.com", "https scheme is not program-like");
    // A file:// URL points at a local file and falls through to the path rules:
    // .exe is whitelisted, so it stays program-like.
    ExpectProgramLike(L"file:///C:/Tools/a.exe", "file scheme exe is program-like");
}

void TestUninstallers() {
    ExpectNotProgramLike(L"C:\\App\\unins000.exe", "unins000.exe is not program-like");
    ExpectNotProgramLike(L"C:\\App\\Uninstall.exe", "Uninstall.exe is not program-like");
    ExpectNotProgramLike(L"C:\\App\\uninstaller.exe", "uninstaller.exe is not program-like");
}

void TestEmpty() {
    ExpectNotProgramLike(L"", "empty target is not program-like");
}

// The three AppsFolder parsing-name shapes (design-spec §2.6): only a real
// absolute path may be shown to the user as a path (§4.2/§4.9).
void TestDisplayablePath() {
    Expect(nimblerun::IsDisplayablePath(L"D:\\Tools\\Notepad3.exe"),
           "absolute path is displayable");
    Expect(nimblerun::IsDisplayablePath(L"c:/Tools/a.lnk"),
           "forward slashes and a lowercase drive are displayable");
    Expect(!nimblerun::IsDisplayablePath(L"Microsoft.WindowsCalculator_8wekyb3d8bbwe!App"),
           "AUMID is not displayable");
    Expect(!nimblerun::IsDisplayablePath(L"{7C5A40EF-A0FB-4BFC-874A-C0F2E0B9FA8E}\\AutoIt3\\Au3Info.exe"),
           "Known Folder GUID relative path is not displayable");
    Expect(!nimblerun::IsDisplayablePath(L"\\\\server\\share\\a.exe"),
           "UNC path is not displayable");
    Expect(!nimblerun::IsDisplayablePath(L""), "empty is not displayable");
    Expect(!nimblerun::IsDisplayablePath(L"C:"), "bare drive is not displayable");
    Expect(!nimblerun::IsDisplayablePath(L"C:a.exe"), "drive-relative path is not displayable");
}

} // namespace

int wmain() {
    TestDisplayablePath();
    TestAumid();
    TestAumidDotsAreNotExtensions();
    TestPathWhitelistHits();
    TestPathWhitelistMisses();
    TestUrlScheme();
    TestUninstallers();
    TestEmpty();
    std::printf("NR-028 app filter check PASSED\n");
    return 0;
}
